### ISSUE TITLE
Add add isolated fault line across isolation barrier.

### ISSUE THREAD

**Issue by liamkinne** [QUT-Motorsport/QUTMS_BMS_V2#1]
Since CANBUS (U5) has been fraught with errors, having a simple BMS fault line to fall back on is really nice. Pin 6 isn't used on the daisy chain header for the boards, so it can be assigned to the fault signal.

What you'll need is an opto-isolator taking a signal from the ATMEL chip. This will need to drive that pin high so the AMS can detect a BMS fault.

**Comment by vivienmu** [comment]
Which pin on the ATMEL chip is the pin to be driven from? In the schematic the only pin unoccupied on U4 is pin 3 (PC1), which according to the datasheet is an input pin

**Comment by vivienmu** [comment]
have opto-isolator (50mA) across isolation barrier from J5 pin 6 to U4 pin 3

**Comment by vivienmu** [comment]
flip opto-isolator

**Comment by vivienmu** [comment]
done
