### ISSUE TITLE
CAN debug lines as header pins

### ISSUE THREAD

**Issue by Sadykow** [QUT-Motorsport/QUTMS_BMS_V2#10]
The best way to debug CAN signal with either logic analyser, or oscilloscope by probing CAN lines.
Adding a few header pins on: TX, RX, CANH, CANL and GND, will be useful.

**Most of the time, the probing is performed on the following combinations: TX, RX, GND or CANH, CANL, GND.**
GND, the ground pin can be only one, but separate from SPI lines, preferably.

LED8 and LED9 are less important than extra header pins, in my opinion. Replacing them at their location is one of the options.

**Comment by vivienmu** [comment]
done, but left LED8 and LED9 untouched.
