### ISSUE TITLE
J1 and J5 connections

### ISSUE THREAD

**Issue by Sadykow** [QUT-Motorsport/QUTMS_BMS_V2#13]
Connections on those ports are in the wrong order if compared with connecting cables. One of those things has to be fixed.

**Comment by vivienmu** [comment]
could you please clarify. when tested for continuity, the wiring of the header pins on the PCB agrees with the schematic.

**Comment by Sadykow** [comment]
Yes, but not wire itself. According to Josh, black and red has to be negative and positive, not CAN lines.

**Comment by liamkinne** [comment]
double checked and the connection on theses are fine, so imma close this.
