### ISSUE TITLE
UART connection

### ISSUE THREAD

**Issue by Sadykow** [QUT-Motorsport/QUTMS_BMS_V2#15]
If you decide to make a UART connection to show judges that data can be obtained from BMS, the SENSOR_* connection has to be reallocated somewhere. Moving them to the location of LED8 or LED7, will not couse any issues.

**Comment by liamkinne** [comment]
Unfortunately can't be done since the atmega64m1 doesn't have enough UART connections. We should probably change the chip in the future since we don't need the power stage controller on this chip anyway.
