### ISSUE TITLE
pin 12, 5 and 13 need to be connected together on U3

### ISSUE THREAD

**Issue by liamkinne** [QUT-Motorsport/QUTMS_BMS_V2#2]

**Comment by vivienmu** [comment]
done

**Comment by Sadykow** [comment]
The 5V connection on VA and LDOIN is still under the question. However, every board was supplied with 5V at those pins. Making two header pins, which then can be bridged together, if necessary, is one of the most reasoning approaches.

On BMS boards, this bridge represented as a yellow wire between MAX and MCP chips.

**Comment by vivienmu** [comment]
we'll change on board if needed

**Comment by Sadykow** [comment]
Adding 0 Om resistor is one of the approaches. Similar to 0R0 on AMS boards.
