### ISSUE TITLE
Optoisolator that turns on the relay doesn't work.

### ISSUE THREAD

**Issue by liamkinne** [QUT-Motorsport/QUTMS_BMS_V2#6]
The opto-isolator (q2) is meant to turn the relay on to let the board take power from the pack only when the accumulator is being used. This currently doesn't work, probably because the opto-isolator can't drive the current of the coil.

R4 may have a value that's too high to turn on the led.

**Comment by vivienmu** [comment]
changed value of R4 to 1K instead of 10K. Circuit works when tested. Done
