### ISSUE TITLE
SPI debug lines as header pins

### ISSUE THREAD

**Issue by Sadykow** [QUT-Motorsport/QUTMS_BMS_V2#9]
So far, to debug SPI, every board had to have an additional five wires, CS, CLC, MOSI, MISO and Ground. Attaching headers pins (similar to the programming one) may avoid extra soldering in future.
CS pins location and need are less vital than actual SPI lines. Placing it either next to SPI or anywhere on the board is entirely optional. However, it is crucial to keep the order of SPi pins to avoid waste of time on picking right one.

**Please keep following order of pins: CS - CLC - MOSI - MISO - GND.**

**Comment by vivienmu** [comment]
done, made comments where cs can be probed on schematic
